apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: devtrack

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        component: api

    spec:
      containers:
        - name: backend

          image: nasirhayat028/devtrack-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: devtrack-config

            - secretRef:
                name: devtrack-secret

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"