apiVersion: v1
# kind: Secret

metadata:
  name: devtrack-secret
  namespace: devtrack

type: Opaque

stringData:
  JWT_SECRET: "<replace-me>"

  MONGO_USERNAME: "<replace-me>"
  MONGO_PASSWORD: "<replace-me>"

  MONGO_URI: "<replace-me>"

