name: DevTrack CI

on:
  push:

jobs:
  verify-runner:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la