name: DevTrack CI

on:
  push:

jobs:
  verify-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check Node Version
        run: node -v

      - name: Check NPM Version
        run: npm -v

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Check Location
        run: pwd

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build